const images = {
    profile: '/images/profile.png',
    certificate: '/images/certificate.png',
    BCAcertificate: '/images/BCAcertificate.jpg',
    tatacertificate: '/images/tata nqt.png',
    resume: '/images/vaibhavResume.png',
    startbusks: '/images/starbuks.png',
    flaashnet: '/images/flaashnet.png',
    boat: '/images/boat.png',
    beyoundchat: '/images/beyoundchat.png',
    gemini: '/images/gemin.png',
    tailwind: '/images/tailwind.png',
    blender: '/images/blender.png',
    figma: '/images/figma.png',
    shopper: '/images/shopper.png',
    chess: '/images/chessgame.png',
    swt: '/images/SWT.png',
    estroverse: '/images/estroverse.png',
}
export default images